before_script:
    - git --version

ps_build:
  stage: build
  script:
    - .\build-ci.ps1
  coverage: '/##teamcity\[buildStatisticValue key=''CodeCoverageS'' value=''(\d+\.?\d*)''\]/'
  artifacts:
    paths:
      - './coverage'
      - './src/TT.Tests/TestResults/TestResults.xml'
    reports:
      junit:
         - './src/TT.Tests/TestResults/TestResults.xml'
    expire_in: 30 days
  tags:
    - powershell
    - windows
    - mssql
