SET NOCOUNT ON;
USE [Stats]
GO
SET IDENTITY_INSERT [dbo].[RestockItems] ON 

INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (1, 2, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (2, 5, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (3, 6, 1, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (4, 129, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (5, 160, 4, 7, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (6, 130, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (7, 133, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (8, 157, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (9, 257, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (10, 258, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (11, 171, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (12, 184, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (13, 390, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (14, 180, 2, 4, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (15, 181, 2, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (16, 182, 1, 2, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (17, 183, 1, 1, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (18, 194, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (19, 231, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (20, 289, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (21, 297, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (22, 209, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (23, 232, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (24, 246, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (25, 261, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (26, 318, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (27, 319, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (28, 339, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (29, 340, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (30, 341, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (31, 405, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (32, 446, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (33, 447, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (34, 448, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (35, 449, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (36, 450, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (37, 451, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (38, 452, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (39, 453, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (40, 454, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (41, 455, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (42, 456, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (43, 457, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (44, 458, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (45, 459, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (46, 460, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (47, 461, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (48, 462, 1, 2, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (49, 463, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (50, 473, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (51, 474, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (52, 475, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (53, 476, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (54, 477, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (55, 478, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (56, 479, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (57, 480, 1, 1, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (58, 481, 1, 1, -3)
SET IDENTITY_INSERT [dbo].[RestockItems] OFF
