SET NOCOUNT ON;
USE [Stats]
GO
SET IDENTITY_INSERT [dbo].[RestockItems] ON 

INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (1, 2, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (2, 5, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (3, 6, 1, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (4, 129, 2, 3, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (5, 160, 4, 7, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (6, 130, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (7, 133, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (8, 157, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (9, 257, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (10, 258, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (11, 171, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (12, 184, 3, 5, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (13, 390, 2, 4, -3)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (14, 180, 2, 4, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (15, 181, 2, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (16, 182, 1, 2, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (17, 183, 1, 1, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (18, 194, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (19, 231, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (20, 289, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (21, 297, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (22, 209, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (23, 232, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (24, 246, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (25, 261, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (26, 318, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (27, 319, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (28, 339, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (29, 340, 1, 3, -15)
INSERT [dbo].[RestockItems] ([Id], [BaseItem_Id], [AmountBeforeRestock], [AmountToRestockTo], [BotId]) VALUES (30, 341, 1, 3, -15)
SET IDENTITY_INSERT [dbo].[RestockItems] OFF
