// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using TT.Web.Controllers.Generated;
namespace TT.Web.Controllers.Generated
{
    public class AdminController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
            static readonly _DonatorsClass s_Donators = new _DonatorsClass();
            public _DonatorsClass Donators { get { return s_Donators; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DonatorsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Create = "Create";
                    public readonly string Edit = "Edit";
                    public readonly string List = "List";
                }
                public readonly string Create = "~/Views/Admin/Donators/Create.cshtml";
                public readonly string Edit = "~/Views/Admin/Donators/Edit.cshtml";
                public readonly string List = "~/Views/Admin/Donators/List.cshtml";
            }
            static readonly _RestockItemsClass s_RestockItems = new _RestockItemsClass();
            public _RestockItemsClass RestockItems { get { return s_RestockItems; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _RestockItemsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Create = "Create";
                    public readonly string Edit = "Edit";
                    public readonly string List = "List";
                }
                public readonly string Create = "~/Views/Admin/RestockItems/Create.cshtml";
                public readonly string Edit = "~/Views/Admin/RestockItems/Edit.cshtml";
                public readonly string List = "~/Views/Admin/RestockItems/List.cshtml";
            }
            static readonly _TomesClass s_Tomes = new _TomesClass();
            public _TomesClass Tomes { get { return s_Tomes; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _TomesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Create = "Create";
                    public readonly string Edit = "Edit";
                    public readonly string List = "List";
                }
                public readonly string Create = "~/Views/Admin/Tomes/Create.cshtml";
                public readonly string Edit = "~/Views/Admin/Tomes/Edit.cshtml";
                public readonly string List = "~/Views/Admin/Tomes/List.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
