// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using TT.Web.Controllers.Generated;
namespace TT.Web.Controllers
{
    public partial class ItemController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ItemController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ItemController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SelfCastSend()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelfCastSend);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoveCurseSend()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveCurseSend);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ReadSkillBook()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReadSkillBook);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowItemDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowItemDetails);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AttachRuneList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AttachRuneList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AttachRune()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AttachRune);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ItemController Actions { get { return MVC.Item; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "item";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "item";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string MyInventory = ("MyInventory").ToLowerInvariant();
            public readonly string SelfCast = ("SelfCast").ToLowerInvariant();
            public readonly string SelfCastSend = ("SelfCastSend").ToLowerInvariant();
            public readonly string RemoveCurse = ("RemoveCurse").ToLowerInvariant();
            public readonly string RemoveCurseSend = ("RemoveCurseSend").ToLowerInvariant();
            public readonly string ReadSkillBook = ("ReadSkillBook").ToLowerInvariant();
            public readonly string ShowItemDetails = ("ShowItemDetails").ToLowerInvariant();
            public readonly string ShowStatsTable = ("ShowStatsTable").ToLowerInvariant();
            public readonly string AttachRuneList = ("AttachRuneList").ToLowerInvariant();
            public readonly string AttachRune = ("AttachRune").ToLowerInvariant();
            public readonly string UnembedRunes = ("UnembedRunes").ToLowerInvariant();
        }


        static readonly ActionParamsClass_SelfCastSend s_params_SelfCastSend = new ActionParamsClass_SelfCastSend();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SelfCastSend SelfCastSendParams { get { return s_params_SelfCastSend; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SelfCastSend
        {
            public readonly string spell = ("spell").ToLowerInvariant();
        }
        static readonly ActionParamsClass_RemoveCurseSend s_params_RemoveCurseSend = new ActionParamsClass_RemoveCurseSend();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveCurseSend RemoveCurseSendParams { get { return s_params_RemoveCurseSend; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveCurseSend
        {
            public readonly string curse = ("curse").ToLowerInvariant();
            public readonly string id = ("id").ToLowerInvariant();
        }
        static readonly ActionParamsClass_ReadSkillBook s_params_ReadSkillBook = new ActionParamsClass_ReadSkillBook();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ReadSkillBook ReadSkillBookParams { get { return s_params_ReadSkillBook; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ReadSkillBook
        {
            public readonly string id = ("id").ToLowerInvariant();
        }
        static readonly ActionParamsClass_ShowItemDetails s_params_ShowItemDetails = new ActionParamsClass_ShowItemDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowItemDetails ShowItemDetailsParams { get { return s_params_ShowItemDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowItemDetails
        {
            public readonly string id = ("id").ToLowerInvariant();
        }
        static readonly ActionParamsClass_AttachRuneList s_params_AttachRuneList = new ActionParamsClass_AttachRuneList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AttachRuneList AttachRuneListParams { get { return s_params_AttachRuneList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AttachRuneList
        {
            public readonly string runeId = ("runeId").ToLowerInvariant();
        }
        static readonly ActionParamsClass_AttachRune s_params_AttachRune = new ActionParamsClass_AttachRune();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AttachRune AttachRuneParams { get { return s_params_AttachRune; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AttachRune
        {
            public readonly string runeId = ("runeId").ToLowerInvariant();
            public readonly string itemId = ("itemId").ToLowerInvariant();
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AttachRuneList = "AttachRuneList";
                public readonly string RemoveCurse = "RemoveCurse";
                public readonly string SelfCast = "SelfCast";
                public readonly string ShowStatsTable = "ShowStatsTable";
                public readonly string SkillBook = "SkillBook";
            }
            public readonly string AttachRuneList = "~/Views/Item/AttachRuneList.cshtml";
            public readonly string RemoveCurse = "~/Views/Item/RemoveCurse.cshtml";
            public readonly string SelfCast = "~/Views/Item/SelfCast.cshtml";
            public readonly string ShowStatsTable = "~/Views/Item/ShowStatsTable.cshtml";
            public readonly string SkillBook = "~/Views/Item/SkillBook.cshtml";
            static readonly _partialClass s_partial = new _partialClass();
            public _partialClass partial { get { return s_partial; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _partialClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string ItemDetails = "ItemDetails";
                    public readonly string PlayPageRuneDetails = "PlayPageRuneDetails";
                    public readonly string RuneDetails = "RuneDetails";
                }
                public readonly string ItemDetails = "~/Views/Item/partial/ItemDetails.cshtml";
                public readonly string PlayPageRuneDetails = "~/Views/Item/partial/PlayPageRuneDetails.cshtml";
                public readonly string RuneDetails = "~/Views/Item/partial/RuneDetails.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ItemController : TT.Web.Controllers.ItemController
    {
        public T4MVC_ItemController() : base(Dummy.Instance) { }

        [NonAction]
        partial void MyInventoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyInventory()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyInventory);
            MyInventoryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SelfCastOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelfCast()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelfCast);
            SelfCastOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SelfCastSendOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string spell);

        [NonAction]
        public override System.Web.Mvc.ActionResult SelfCastSend(string spell)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SelfCastSend);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "spell", spell);
            SelfCastSendOverride(callInfo, spell);
            return callInfo;
        }

        [NonAction]
        partial void RemoveCurseOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemoveCurse()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveCurse);
            RemoveCurseOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RemoveCurseSendOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string curse, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult RemoveCurseSend(string curse, int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoveCurseSend);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "curse", curse);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoveCurseSendOverride(callInfo, curse, id);
            return callInfo;
        }

        [NonAction]
        partial void ReadSkillBookOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ReadSkillBook(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ReadSkillBook);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ReadSkillBookOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShowItemDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowItemDetails(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowItemDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ShowItemDetailsOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ShowStatsTableOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowStatsTable()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowStatsTable);
            ShowStatsTableOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AttachRuneListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int runeId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AttachRuneList(int runeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AttachRuneList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "runeId", runeId);
            AttachRuneListOverride(callInfo, runeId);
            return callInfo;
        }

        [NonAction]
        partial void AttachRuneOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int runeId, int itemId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AttachRune(int runeId, int itemId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AttachRune);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "runeId", runeId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemId", itemId);
            AttachRuneOverride(callInfo, runeId, itemId);
            return callInfo;
        }

        [NonAction]
        partial void UnembedRunesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UnembedRunes()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnembedRunes);
            UnembedRunesOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
