// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using TT.Web.Controllers.Generated;
namespace TT.Web.Controllers
{
    public partial class QuestController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public QuestController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected QuestController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult StartQuest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StartQuest);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Choice()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Choice);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EndQuest()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EndQuest);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public QuestController Actions { get { return MVC.Quest; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "quest";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "quest";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string StartQuest = ("StartQuest").ToLowerInvariant();
            public readonly string QuestsAvailableHere = ("QuestsAvailableHere").ToLowerInvariant();
            public readonly string Questing = ("Questing").ToLowerInvariant();
            public readonly string Quest = ("Quest").ToLowerInvariant();
            public readonly string Choice = ("Choice").ToLowerInvariant();
            public readonly string Abandon = ("Abandon").ToLowerInvariant();
            public readonly string AbandonConfirm = ("AbandonConfirm").ToLowerInvariant();
            public readonly string EndQuest = ("EndQuest").ToLowerInvariant();
            public readonly string ResetQuests = ("ResetQuests").ToLowerInvariant();
        }


        static readonly ActionParamsClass_StartQuest s_params_StartQuest = new ActionParamsClass_StartQuest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_StartQuest StartQuestParams { get { return s_params_StartQuest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_StartQuest
        {
            public readonly string Id = ("Id").ToLowerInvariant();
        }
        static readonly ActionParamsClass_Choice s_params_Choice = new ActionParamsClass_Choice();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Choice ChoiceParams { get { return s_params_Choice; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Choice
        {
            public readonly string Id = ("Id").ToLowerInvariant();
        }
        static readonly ActionParamsClass_EndQuest s_params_EndQuest = new ActionParamsClass_EndQuest();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EndQuest EndQuestParams { get { return s_params_EndQuest; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EndQuest
        {
            public readonly string restore = ("restore").ToLowerInvariant();
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Abandon = "Abandon";
                public readonly string Quest = "Quest";
                public readonly string Questing = "Questing";
                public readonly string QuestsAvailableHere = "QuestsAvailableHere";
            }
            public readonly string Abandon = "~/Views/Quest/Abandon.cshtml";
            public readonly string Quest = "~/Views/Quest/Quest.cshtml";
            public readonly string Questing = "~/Views/Quest/Questing.cshtml";
            public readonly string QuestsAvailableHere = "~/Views/Quest/QuestsAvailableHere.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_QuestController : TT.Web.Controllers.QuestController
    {
        public T4MVC_QuestController() : base(Dummy.Instance) { }

        [NonAction]
        partial void StartQuestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult StartQuest(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StartQuest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            StartQuestOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void QuestsAvailableHereOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult QuestsAvailableHere()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuestsAvailableHere);
            QuestsAvailableHereOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void QuestingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Questing()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Questing);
            QuestingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void QuestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Quest()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Quest);
            QuestOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChoiceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Choice(int Id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Choice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Id", Id);
            ChoiceOverride(callInfo, Id);
            return callInfo;
        }

        [NonAction]
        partial void AbandonOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Abandon()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Abandon);
            AbandonOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AbandonConfirmOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AbandonConfirm()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AbandonConfirm);
            AbandonConfirmOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EndQuestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool restore);

        [NonAction]
        public override System.Web.Mvc.ActionResult EndQuest(bool restore)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EndQuest);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "restore", restore);
            EndQuestOverride(callInfo, restore);
            return callInfo;
        }

        [NonAction]
        partial void ResetQuestsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetQuests()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetQuests);
            ResetQuestsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
