// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using TT.Web.Controllers.Generated;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static TT.Web.Controllers.AccountController Account = new TT.Web.Controllers.T4MVC_AccountController();
    public static TT.Web.Controllers.Admin.DonatorController Donator = new TT.Web.Controllers.Admin.T4MVC_DonatorController();
    public static TT.Web.Controllers.Admin.RestockItemController RestockItem = new TT.Web.Controllers.Admin.T4MVC_RestockItemController();
    public static TT.Web.Controllers.Admin.TomeController Tome = new TT.Web.Controllers.Admin.T4MVC_TomeController();
    public static TT.Web.Controllers.ChatController Chat = new TT.Web.Controllers.T4MVC_ChatController();
    public static TT.Web.Controllers.ContributionController Contribution = new TT.Web.Controllers.T4MVC_ContributionController();
    public static TT.Web.Controllers.CovenantController Covenant = new TT.Web.Controllers.T4MVC_CovenantController();
    public static TT.Web.Controllers.DuelController Duel = new TT.Web.Controllers.T4MVC_DuelController();
    public static TT.Web.Controllers.InfoController Info = new TT.Web.Controllers.T4MVC_InfoController();
    public static TT.Web.Controllers.ItemController Item = new TT.Web.Controllers.T4MVC_ItemController();
    public static TT.Web.Controllers.LeaderboardController Leaderboard = new TT.Web.Controllers.T4MVC_LeaderboardController();
    public static TT.Web.Controllers.MessagesController Messages = new TT.Web.Controllers.T4MVC_MessagesController();
    public static TT.Web.Controllers.ModeratorController Moderator = new TT.Web.Controllers.T4MVC_ModeratorController();
    public static TT.Web.Controllers.NPCController NPC = new TT.Web.Controllers.T4MVC_NPCController();
    public static TT.Web.Controllers.PvPAdminController PvPAdmin = new TT.Web.Controllers.T4MVC_PvPAdminController();
    public static TT.Web.Controllers.PvPController PvP = new TT.Web.Controllers.T4MVC_PvPController();
    public static TT.Web.Controllers.QuestController Quest = new TT.Web.Controllers.T4MVC_QuestController();
    public static TT.Web.Controllers.QuestWriterController QuestWriter = new TT.Web.Controllers.T4MVC_QuestWriterController();
    public static TT.Web.Controllers.ReportController Report = new TT.Web.Controllers.T4MVC_ReportController();
    public static TT.Web.Controllers.SettingsController Settings = new TT.Web.Controllers.T4MVC_SettingsController();
    public static TT.Web.Controllers.TransformaniaTimeController TransformaniaTime = new TT.Web.Controllers.T4MVC_TransformaniaTimeController();
    public static TT.Web.Controllers.Generated.AdminController Admin = new TT.Web.Controllers.Generated.AdminController();
    public static TT.Web.Controllers.Generated.SharedController Shared = new TT.Web.Controllers.Generated.SharedController();
}

namespace TT.Web.Controllers.Generated
{
}

#pragma warning disable 0436
namespace TT.Web.Controllers.Generated
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}
#pragma warning restore 0436

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        public const string UrlPath = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string boxesResize_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/boxesResize.min.js") ? Url("boxesResize.min.js") : Url("boxesResize.js");
        public static readonly string Character_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Character.min.js") ? Url("Character.min.js") : Url("Character.js");
        public static readonly string CharacterLoader_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/CharacterLoader.min.js") ? Url("CharacterLoader.min.js") : Url("CharacterLoader.js");
        public static readonly string game_discus_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_discus.min.js") ? Url("game_discus.min.js") : Url("game_discus.js");
        public static readonly string game_dpong_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_dpong.min.js") ? Url("game_dpong.min.js") : Url("game_dpong.js");
        public static readonly string game_memory_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_memory.min.js") ? Url("game_memory.min.js") : Url("game_memory.js");
        public static readonly string game_popup_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_popup.min.js") ? Url("game_popup.min.js") : Url("game_popup.js");
        public static readonly string game_reflex_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_reflex.min.js") ? Url("game_reflex.min.js") : Url("game_reflex.js");
        public static readonly string game_roulette_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_roulette.min.js") ? Url("game_roulette.min.js") : Url("game_roulette.js");
        public static readonly string game_sequence_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/game_sequence.min.js") ? Url("game_sequence.min.js") : Url("game_sequence.js");
        public static readonly string GenericCharData_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GenericCharData.min.js") ? Url("GenericCharData.min.js") : Url("GenericCharData.js");
        public static readonly string GenericPlayerData_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/GenericPlayerData.min.js") ? Url("GenericPlayerData.min.js") : Url("GenericPlayerData.js");
        public static readonly string jquery_2_1_0_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-2.1.0.intellisense.min.js") ? Url("jquery-2.1.0.intellisense.min.js") : Url("jquery-2.1.0.intellisense.js");
        public static readonly string jquery_2_1_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-2.1.0.min.js") ? Url("jquery-2.1.0.min.js") : Url("jquery-2.1.0.js");
        public static readonly string jquery_2_1_0_min_js = Url("jquery-2.1.0.min.js");
        public static readonly string jquery_2_1_0_min_map = Url("jquery-2.1.0.min.map");
        public static readonly string jquery_ui_1_10_4_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-ui-1.10.4.min.js") ? Url("jquery-ui-1.10.4.min.js") : Url("jquery-ui-1.10.4.js");
        public static readonly string jquery_ui_1_10_4_min_js = Url("jquery-ui-1.10.4.min.js");
        public static readonly string jquery_animate_color_min_js = Url("jquery.animate-color.min.js");
        public static readonly string jquery_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.min.js") ? Url("jquery.min.js") : Url("jquery.js");
        public static readonly string jquery_mobile_custom_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.mobile.custom.min.js") ? Url("jquery.mobile.custom.min.js") : Url("jquery.mobile.custom.js");
        public static readonly string jquery_mobile_custom_min_js = Url("jquery.mobile.custom.min.js");
        public static readonly string jquery_mobile_doubletap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.mobile.doubletap.min.js") ? Url("jquery.mobile.doubletap.min.js") : Url("jquery.mobile.doubletap.js");
        public static readonly string jquery_rotate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.rotate.min.js") ? Url("jquery.rotate.min.js") : Url("jquery.rotate.js");
        public static readonly string jquery_signalR_2_0_3_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.signalR-2.0.3.min.js") ? Url("jquery.signalR-2.0.3.min.js") : Url("jquery.signalR-2.0.3.js");
        public static readonly string jquery_signalR_2_0_3_min_js = Url("jquery.signalR-2.0.3.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jQueryRotate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jQueryRotate.min.js") ? Url("jQueryRotate.min.js") : Url("jQueryRotate.js");
        public static readonly string jQueryRotateCompressed_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jQueryRotateCompressed.min.js") ? Url("jQueryRotateCompressed.min.js") : Url("jQueryRotateCompressed.js");
        public static readonly string knockout_3_0_0_debug_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout-3.0.0.debug.min.js") ? Url("knockout-3.0.0.debug.min.js") : Url("knockout-3.0.0.debug.js");
        public static readonly string knockout_3_0_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/knockout-3.0.0.min.js") ? Url("knockout-3.0.0.min.js") : Url("knockout-3.0.0.js");
        public static readonly string leaderboardDropdown_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/leaderboardDropdown.min.js") ? Url("leaderboardDropdown.min.js") : Url("leaderboardDropdown.js");
        public static readonly string modernizr_2_7_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/modernizr-2.7.1.min.js") ? Url("modernizr-2.7.1.min.js") : Url("modernizr-2.7.1.js");
        public static readonly string moment_with_locales_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment-with-locales.min.js") ? Url("moment-with-locales.min.js") : Url("moment-with-locales.js");
        public static readonly string moment_with_locales_min_js = Url("moment-with-locales.min.js");
        public static readonly string moment_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/moment.min.js") ? Url("moment.min.js") : Url("moment.js");
        public static readonly string moment_min_js = Url("moment.min.js");
        public static readonly string newCharacter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/newCharacter.min.js") ? Url("newCharacter.min.js") : Url("newCharacter.js");
        public static readonly string notices_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/notices.min.js") ? Url("notices.min.js") : Url("notices.js");
        public static readonly string pastRounds_json = Url("pastRounds.json");
        public static readonly string randomFirstLastNames_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/randomFirstLastNames.min.js") ? Url("randomFirstLastNames.min.js") : Url("randomFirstLastNames.js");
        public static readonly string script_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/script.min.js") ? Url("script.min.js") : Url("script.js");
        public static readonly string suggestedLength_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/suggestedLength.min.js") ? Url("suggestedLength.min.js") : Url("suggestedLength.js");
        public static readonly string tt_api_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tt.api.min.js") ? Url("tt.api.min.js") : Url("tt.api.js");
        public static readonly string tt_chat_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tt.chat.min.js") ? Url("tt.chat.min.js") : Url("tt.chat.js");
        public static readonly string tt_chat_messages_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tt.chat.messages.min.js") ? Url("tt.chat.messages.min.js") : Url("tt.chat.messages.js");
        public static readonly string tt_chat_operations_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tt.chat.operations.min.js") ? Url("tt.chat.operations.min.js") : Url("tt.chat.operations.js");
        public static readonly string tt_chat_userList_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tt.chat.userList.min.js") ? Url("tt.chat.userList.min.js") : Url("tt.chat.userList.js");
        public static readonly string tt_config_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/tt.config.min.js") ? Url("tt.config.min.js") : Url("tt.config.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        public const string UrlPath = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string custom_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/custom.min.css") ? Url("custom.min.css") : Url("custom.css");
        public static readonly string custom_min_css = Url("custom.min.css");
        public static readonly string custom_scss = Url("custom.scss");
        public static readonly string mystyle_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/mystyle.min.css") ? Url("mystyle.min.css") : Url("mystyle.css");
        public static readonly string ng_animation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/ng-animation.min.css") ? Url("ng-animation.min.css") : Url("ng-animation.css");
        public static readonly string PvP_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/PvP.min.css") ? Url("PvP.min.css") : Url("PvP.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            public const string UrlPath = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class @base {
                public const string UrlPath = "~/Content/themes/base";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    public const string UrlPath = "~/Content/themes/base/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    public static readonly string animated_overlay_gif = Url("animated-overlay.gif");
                    public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                    public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                    public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                    public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                    public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                    public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                    public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                    public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                    public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                    public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                    public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                    public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                    public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                }
            
                public static readonly string jquery_ui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery-ui.min.css") ? Url("jquery-ui.min.css") : Url("jquery-ui.css");
                public static readonly string jquery_ui_accordion_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.accordion.min.css") ? Url("jquery.ui.accordion.min.css") : Url("jquery.ui.accordion.css");
                public static readonly string jquery_ui_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.all.min.css") ? Url("jquery.ui.all.min.css") : Url("jquery.ui.all.css");
                public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.autocomplete.min.css") ? Url("jquery.ui.autocomplete.min.css") : Url("jquery.ui.autocomplete.css");
                public static readonly string jquery_ui_base_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.base.min.css") ? Url("jquery.ui.base.min.css") : Url("jquery.ui.base.css");
                public static readonly string jquery_ui_button_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.button.min.css") ? Url("jquery.ui.button.min.css") : Url("jquery.ui.button.css");
                public static readonly string jquery_ui_core_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.core.min.css") ? Url("jquery.ui.core.min.css") : Url("jquery.ui.core.css");
                public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.datepicker.min.css") ? Url("jquery.ui.datepicker.min.css") : Url("jquery.ui.datepicker.css");
                public static readonly string jquery_ui_dialog_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.dialog.min.css") ? Url("jquery.ui.dialog.min.css") : Url("jquery.ui.dialog.css");
                public static readonly string jquery_ui_menu_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.menu.min.css") ? Url("jquery.ui.menu.min.css") : Url("jquery.ui.menu.css");
                public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.progressbar.min.css") ? Url("jquery.ui.progressbar.min.css") : Url("jquery.ui.progressbar.css");
                public static readonly string jquery_ui_resizable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.resizable.min.css") ? Url("jquery.ui.resizable.min.css") : Url("jquery.ui.resizable.css");
                public static readonly string jquery_ui_selectable_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.selectable.min.css") ? Url("jquery.ui.selectable.min.css") : Url("jquery.ui.selectable.css");
                public static readonly string jquery_ui_slider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.slider.min.css") ? Url("jquery.ui.slider.min.css") : Url("jquery.ui.slider.css");
                public static readonly string jquery_ui_spinner_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.spinner.min.css") ? Url("jquery.ui.spinner.min.css") : Url("jquery.ui.spinner.css");
                public static readonly string jquery_ui_tabs_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.tabs.min.css") ? Url("jquery.ui.tabs.min.css") : Url("jquery.ui.tabs.css");
                public static readonly string jquery_ui_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.theme.min.css") ? Url("jquery.ui.theme.min.css") : Url("jquery.ui.theme.css");
                public static readonly string jquery_ui_tooltip_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(UrlPath + "/jquery.ui.tooltip.min.css") ? Url("jquery.ui.tooltip.min.css") : Url("jquery.ui.tooltip.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class minified {
                    public const string UrlPath = "~/Content/themes/base/minified";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class images {
                        public const string UrlPath = "~/Content/themes/base/minified/images";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(UrlPath); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(UrlPath + "/" + fileName); }
                        public static readonly string animated_overlay_gif = Url("animated-overlay.gif");
                        public static readonly string ui_bg_flat_0_aaaaaa_40x100_png = Url("ui-bg_flat_0_aaaaaa_40x100.png");
                        public static readonly string ui_bg_flat_75_ffffff_40x100_png = Url("ui-bg_flat_75_ffffff_40x100.png");
                        public static readonly string ui_bg_glass_55_fbf9ee_1x400_png = Url("ui-bg_glass_55_fbf9ee_1x400.png");
                        public static readonly string ui_bg_glass_65_ffffff_1x400_png = Url("ui-bg_glass_65_ffffff_1x400.png");
                        public static readonly string ui_bg_glass_75_dadada_1x400_png = Url("ui-bg_glass_75_dadada_1x400.png");
                        public static readonly string ui_bg_glass_75_e6e6e6_1x400_png = Url("ui-bg_glass_75_e6e6e6_1x400.png");
                        public static readonly string ui_bg_glass_95_fef1ec_1x400_png = Url("ui-bg_glass_95_fef1ec_1x400.png");
                        public static readonly string ui_bg_highlight_soft_75_cccccc_1x100_png = Url("ui-bg_highlight-soft_75_cccccc_1x100.png");
                        public static readonly string ui_icons_222222_256x240_png = Url("ui-icons_222222_256x240.png");
                        public static readonly string ui_icons_2e83ff_256x240_png = Url("ui-icons_2e83ff_256x240.png");
                        public static readonly string ui_icons_454545_256x240_png = Url("ui-icons_454545_256x240.png");
                        public static readonly string ui_icons_888888_256x240_png = Url("ui-icons_888888_256x240.png");
                        public static readonly string ui_icons_cd0a0a_256x240_png = Url("ui-icons_cd0a0a_256x240.png");
                    }
                
                    public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
                    public static readonly string jquery_ui_accordion_min_css = Url("jquery.ui.accordion.min.css");
                    public static readonly string jquery_ui_autocomplete_min_css = Url("jquery.ui.autocomplete.min.css");
                    public static readonly string jquery_ui_button_min_css = Url("jquery.ui.button.min.css");
                    public static readonly string jquery_ui_core_min_css = Url("jquery.ui.core.min.css");
                    public static readonly string jquery_ui_datepicker_min_css = Url("jquery.ui.datepicker.min.css");
                    public static readonly string jquery_ui_dialog_min_css = Url("jquery.ui.dialog.min.css");
                    public static readonly string jquery_ui_menu_min_css = Url("jquery.ui.menu.min.css");
                    public static readonly string jquery_ui_progressbar_min_css = Url("jquery.ui.progressbar.min.css");
                    public static readonly string jquery_ui_resizable_min_css = Url("jquery.ui.resizable.min.css");
                    public static readonly string jquery_ui_selectable_min_css = Url("jquery.ui.selectable.min.css");
                    public static readonly string jquery_ui_slider_min_css = Url("jquery.ui.slider.min.css");
                    public static readonly string jquery_ui_spinner_min_css = Url("jquery.ui.spinner.min.css");
                    public static readonly string jquery_ui_tabs_min_css = Url("jquery.ui.tabs.min.css");
                    public static readonly string jquery_ui_theme_min_css = Url("jquery.ui.theme.min.css");
                    public static readonly string jquery_ui_tooltip_min_css = Url("jquery.ui.tooltip.min.css");
                }
            
            }
        
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public static readonly string _references_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/_references.js"); 
                public static readonly string boxesResize_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/boxesResize.js"); 
                public static readonly string Character_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/Character.js"); 
                public static readonly string CharacterLoader_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/CharacterLoader.js"); 
                public static readonly string game_discus_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_discus.js"); 
                public static readonly string game_dpong_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_dpong.js"); 
                public static readonly string game_memory_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_memory.js"); 
                public static readonly string game_popup_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_popup.js"); 
                public static readonly string game_reflex_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_reflex.js"); 
                public static readonly string game_roulette_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_roulette.js"); 
                public static readonly string game_sequence_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/game_sequence.js"); 
                public static readonly string GenericCharData_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/GenericCharData.js"); 
                public static readonly string GenericPlayerData_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/GenericPlayerData.js"); 
                public static readonly string jquery_2_1_0_intellisense_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-2.1.0.intellisense.js"); 
                public static readonly string jquery_2_1_0_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-2.1.0.js"); 
                public static readonly string jquery_2_1_0_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-2.1.0.min.js"); 
                public static readonly string jquery_ui_1_10_4_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-ui-1.10.4.js"); 
                public static readonly string jquery_ui_1_10_4_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery-ui-1.10.4.min.js"); 
                public static readonly string jquery_animate_color_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.animate-color.min.js"); 
                public static readonly string jquery_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.js"); 
                public static readonly string jquery_mobile_custom_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.mobile.custom.js"); 
                public static readonly string jquery_mobile_custom_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.mobile.custom.min.js"); 
                public static readonly string jquery_mobile_doubletap_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.mobile.doubletap.js"); 
                public static readonly string jquery_rotate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.rotate.js"); 
                public static readonly string jquery_signalR_2_0_3_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.signalR-2.0.3.js"); 
                public static readonly string jquery_signalR_2_0_3_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.signalR-2.0.3.min.js"); 
                public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.unobtrusive-ajax.js"); 
                public static readonly string jquery_unobtrusive_ajax_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jquery.unobtrusive-ajax.min.js"); 
                public static readonly string jQueryRotate_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jQueryRotate.js"); 
                public static readonly string jQueryRotateCompressed_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/jQueryRotateCompressed.js"); 
                public static readonly string knockout_3_0_0_debug_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/knockout-3.0.0.debug.js"); 
                public static readonly string knockout_3_0_0_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/knockout-3.0.0.js"); 
                public static readonly string leaderboardDropdown_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/leaderboardDropdown.js"); 
                public static readonly string modernizr_2_7_1_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/modernizr-2.7.1.js"); 
                public static readonly string moment_with_locales_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment-with-locales.js"); 
                public static readonly string moment_with_locales_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment-with-locales.min.js"); 
                public static readonly string moment_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment.js"); 
                public static readonly string moment_min_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/moment.min.js"); 
                public static readonly string newCharacter_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/newCharacter.js"); 
                public static readonly string notices_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/notices.js"); 
                public static readonly string randomFirstLastNames_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/randomFirstLastNames.js"); 
                public static readonly string script_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/script.js"); 
                public static readonly string suggestedLength_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/suggestedLength.js"); 
                public static readonly string tt_api_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/tt.api.js"); 
                public static readonly string tt_chat_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/tt.chat.js"); 
                public static readonly string tt_chat_messages_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/tt.chat.messages.js"); 
                public static readonly string tt_chat_operations_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/tt.chat.operations.js"); 
                public static readonly string tt_chat_userList_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/tt.chat.userList.js"); 
                public static readonly string tt_config_js = T4MVCHelpers.ProcessAssetPath("~/Scripts/tt.config.js"); 
            }
        }
        public static partial class Content 
        {
            public static partial class themes 
            {
                public static partial class @base 
                {
                    public static partial class images 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class minified 
                    {
                        public static partial class images 
                        {
                            public static class Assets
                            {
                            }
                        }
                        public static class Assets
                        {
                            public static readonly string jquery_ui_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery-ui.min.css");
                            public static readonly string jquery_ui_accordion_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.accordion.min.css");
                            public static readonly string jquery_ui_autocomplete_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.autocomplete.min.css");
                            public static readonly string jquery_ui_button_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.button.min.css");
                            public static readonly string jquery_ui_core_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.core.min.css");
                            public static readonly string jquery_ui_datepicker_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.datepicker.min.css");
                            public static readonly string jquery_ui_dialog_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.dialog.min.css");
                            public static readonly string jquery_ui_menu_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.menu.min.css");
                            public static readonly string jquery_ui_progressbar_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.progressbar.min.css");
                            public static readonly string jquery_ui_resizable_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.resizable.min.css");
                            public static readonly string jquery_ui_selectable_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.selectable.min.css");
                            public static readonly string jquery_ui_slider_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.slider.min.css");
                            public static readonly string jquery_ui_spinner_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.spinner.min.css");
                            public static readonly string jquery_ui_tabs_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.tabs.min.css");
                            public static readonly string jquery_ui_theme_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.theme.min.css");
                            public static readonly string jquery_ui_tooltip_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/minified/jquery.ui.tooltip.min.css");
                        }
                    }
                    public static class Assets
                    {
                        public static readonly string jquery_ui_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery-ui.css");
                        public static readonly string jquery_ui_accordion_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.accordion.css");
                        public static readonly string jquery_ui_all_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.all.css");
                        public static readonly string jquery_ui_autocomplete_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.autocomplete.css");
                        public static readonly string jquery_ui_base_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.base.css");
                        public static readonly string jquery_ui_button_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.button.css");
                        public static readonly string jquery_ui_core_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.core.css");
                        public static readonly string jquery_ui_datepicker_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.datepicker.css");
                        public static readonly string jquery_ui_dialog_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.dialog.css");
                        public static readonly string jquery_ui_menu_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.menu.css");
                        public static readonly string jquery_ui_progressbar_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.progressbar.css");
                        public static readonly string jquery_ui_resizable_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.resizable.css");
                        public static readonly string jquery_ui_selectable_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.selectable.css");
                        public static readonly string jquery_ui_slider_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.slider.css");
                        public static readonly string jquery_ui_spinner_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.spinner.css");
                        public static readonly string jquery_ui_tabs_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.tabs.css");
                        public static readonly string jquery_ui_theme_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.theme.css");
                        public static readonly string jquery_ui_tooltip_css = T4MVCHelpers.ProcessAssetPath("~/Content/themes/base/jquery.ui.tooltip.css");
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public static readonly string bootstrap_min_css = T4MVCHelpers.ProcessAssetPath("~/Content/bootstrap.min.css");
                public static readonly string custom_css = T4MVCHelpers.ProcessAssetPath("~/Content/custom.css");
                public static readonly string mystyle_css = T4MVCHelpers.ProcessAssetPath("~/Content/mystyle.css");
                public static readonly string ng_animation_css = T4MVCHelpers.ProcessAssetPath("~/Content/ng-animation.css");
                public static readonly string PvP_css = T4MVCHelpers.ProcessAssetPath("~/Content/PvP.css");
                public static readonly string Site_css = T4MVCHelpers.ProcessAssetPath("~/Content/Site.css");
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    private static string ProcessAssetPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and should retain this prefix
        return virtualPath;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;
    public static Func<string, string> ProcessAssetPath = ProcessAssetPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


